### ISSUE TITLE
msg-API does not return values

### ISSUE THREAD

**Issue by martin3000** [cyr-ius/audiconnectpy#3]
The API at https://app-api.live-my.audi.com/vgql/v1/graphql successfully returns the main data for my car - VIN, Model and so on.
But then the API at https://msg.volkswagen.de/fs-car/bs/vsr/v1/Audi/DE/vehicles/WAUZZZ8T19A012345/xxxx always returns:
{"error":{
"errorCode":"VSR.security.9007",
"description":"The referenced vehicle with VIN: WAUZZZ8T19A012345 could not be found or has no association to the given User" }}
The server is the "home_region" from services.py.
What could be the reason for this?
In the black Audi app I can see the details like mileage.

**Comment by martin3000** [comment]
I'm doing some debugging and I that the call
>https://mal-1a.prd.ece.vwg-connect.com/api/cs/vds/v1/vehicles/WAUZZZ8T19A012345/homeRegion

gets a response of
>ServiceNotFoundError:(404, {'error': {'errorCode': 'mbbc.vds.sopCalculationFailed', 'description': 'Could not calculate the SOP for vin=WAUZZZ8T19A012345'}})

**Comment by vvmichielvv** [comment]
Almost the same problem here: i also get the the error as stated in you initial message. However, the 'Could not calculate the SOP' error I do not get - it resolves as an OK in my debug log. Furthermore, Honkflash does return a 200 on ' https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/rhf/v1/Audi/NL/configuration'...the others do either 403 or 502. 

Did they change the API (again)?

**Comment by rvoitenko** [comment]
> Almost the same problem here: i also get the the error as stated in you initial message. However, the 'Could not calculate the SOP' error I do not get - it resolves as an OK in my debug log. Furthermore, Honkflash does return a 200 on ' https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car/bs/rhf/v1/Audi/NL/configuration'...the others do either 403 or 502.
> 
> Did they change the API (again)?

yes, old API has been completely deprecated - https://github.com/audiconnect/audi_connect_ha/issues/228
so audiconnectpy need an update as well.

**Comment by cyr-ius** [comment]
Fix with 2.5.5 version
