### ISSUE TITLE
API updated and so no longer working?

### ISSUE THREAD

**Issue by vvmichielvv** [cyr-ius/audiconnectpy#53]
Hi there!

Very happy to use this module! I too got the '(Error occurred while communicating with Audi Connect.)'. Logged into the app etc. but the error remains. When debugging, i notice that the code is retrieving all the info from the API, but somehow it still generates an error. More over, the data it retrieves from the API is not properly stored by the code, so i cannot access it: 

`import asyncio
from aiohttp import ClientSession

# Import the audiconnectpy package.
from audiconnectpy import AudiConnect

import logging
logging.basicConfig(level=logging.DEBUG) 

VW_USERNAME = "xxxxxxxxxxxxxxxx"
VW_PASSWORD = "xxxxxxxxxxxxxxxx"
COUNTRY = "NL"
SPIN = "xxxxxxxxxxxxxxxx"

async def main():
    async with ClientSession() as session:
        api = AudiConnect(session, VW_USERNAME, VW_PASSWORD, COUNTRY, SPIN)
        await api.async_login()
        
        print(api.vehicles[0])

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())`

vehicle dump in python:

`
Vehicle(vin='xxxxxxxxxxxxxxxx', uris={'client_id': 'xxxxxxxxxxxxxxxx@apps_vw-dilab_com', 'audi_url': 'https://emea.bff.cariad.digital/login/v1/audi', 'profil_url': 'https://customer-profile.vwgroup.io/v3', 'mbb_url': 'https://mbboauth-1d.prd.ece.vwg-connect.com/mbbcoauth', 'here_url': 'https://csm.cc.api.here.com/api/v1', 'mdk_url': 'https://emea.bff.cariad.digital/', 'cv_url': 'https://emea.bff.cariad.digital', 'user_url': 'https://userinformationservice.apps.emea.vwapps.io', 'vdgqs_url': None, 'authorization_endpoint': 'https://identity.vwgroup.io/oidc/v1/authorize', 'token_endpoint': 'https://emea.bff.cariad.digital/login/v1/idk/token', 'revocation_endpoint': 'https://emea.bff.cariad.digital/login/v1/idk/revoke', 'language': 'nl', 'country': 'NL'}, auth=<audiconnectpy.auth.Auth object at 0x7f67d459cb10>, fill_region=FillRegion(url='https://fal-3a.prd.eu.dp.vwg-connect.com/fs-car', url_setter='https://mal-3a.prd.eu.dp.vwg-connect.com/api'), spin='xxxxxxxxxxxxxxxx', last_access=None, last_update=None, is_moving=None, capabilities_supported=None, position_supported=None, locations_supported=None, trips_supported=None, position=None, climatisation_timers=[])`

**Comment by cyr-ius** [comment]
Fixed  , test vlPlease test 2.5.5 version

**Comment by tieskuh** [comment]
Works again. Thanks 🙏
